version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rickandmorty
      MONGO_INITDB_ROOT_PASSWORD: challenge
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
